--- # ---
production:
  password: e97b24977ac823b7d61ea8238545221b
  theme_id: 80962650161 #--- Production
  store: marissa-sandbox.myshopify.com
  ignores:
    - .themeignore

development:
  password: e97b24977ac823b7d61ea8238545221b
  theme_id: 80962682929 #--- Develop
  store: marissa-sandbox.myshopify.com
  ignores:
    - .themeignore
